HPC-8242 - FTS Admin setup
UN-OCHA/hpc-cdm pull request #305
Opened 2022-06-01 14:29 UTC by czmj

FTS Admin rewrite has been started here, in the CDM monorepo, as it relies on the libs in this repository.

The [hpc-apps-core](https://github.com/UN-OCHA/hpc-apps-core) repository was originally created to house these libs and [hpc-ftsadmin-site](https://github.com/UN-OCHA/hpc-ftsadmin-site) repository was created to host FTS Admin rewrite.

[hpc-apps-core](https://github.com/UN-OCHA/hpc-apps-core) was meant to be imported in both CDM (here) and FTS Admin (in [hpc-ftsadmin-site](https://github.com/UN-OCHA/hpc-ftsadmin-site)), but this has not been possible without major changes to CDM and potentially removing Nx from CDM, due to the way Typescript/Nx are set up.

CDM is used in TS config of hpc_service as its [baseUrl is set](https://github.com/UN-OCHA/hpc_service/blob/f37342188c768a2c1de3876dd3db0c85047ded40/tsconfig.json#L16) to external/hpc_cdm, but that prevents other external paths to be included.

Extracting [hpc-apps-core](https://github.com/UN-OCHA/hpc-apps-core) into npm package, like it's done for [hpc-api-core](https://github.com/UN-OCHA/hpc-api-core) may be an option in the future.

2022-06-01 14:32 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2022-06-08 09:07 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2022-06-23 06:36 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2022-06-27 15:28 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2022-06-29 12:31 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2022-07-04 07:58 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2022-07-04 11:21 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2022-07-18 15:47 UTC, Pl217 requested changes
Let's extract work on updating MUI to a separate PR, because it mostly deals with updating CDM.  Also, that commit (b1ccf86e1deea5a1f77989e4328fa5ac13c22286) reorganizes imports too much, which makes changes harder to read. Please open this as a separate PR, where second commit can make import reordering, if you want.

Second complaint is that 1981dd27efcaef4700fbda732d62726768c5c6f3 makes same changes as #307. Besides me wanting changes requested in that PR, I also don't think committing like this is desirable. Your first commit copies most of the things from CDM to FTS Admin, which includes the tests, which are then "fixed" in 1981dd27efcaef4700fbda732d62726768c5c6f3. I would prefer correct tests from the first commit or do a separate commit which sets up testing in FTS admin app.

Last complaint is that we're starting a new project, adding a new app to the repo, yet no documentation is changed. We need to document that we have utilized this repo for another app, document how to start the server on your local, etc. Also, this PR's first comment should document what we're doing here and how we ended up reusing CDM repo. We opened [hpc-ftsadmin-site](https://github.com/UN-OCHA/hpc-ftsadmin-site) and [hpc-apps-core](https://github.com/UN-OCHA/hpc-apps-core) repos, yet we're still not using them. All of the discussions we had around this should be documented for everyone else (now and in the future) to see.

2022-07-18 15:47 UTC, Pl217 commented on apps/hpc-ftsadmin/src/i18n/langs/fr.json
> +    "flows": "Search Funding Flows"
This seems like the only untranslated string.

2022-07-21 14:15 UTC, czmj commented
Moving this to Pending prior merge as it depends on HPC-8326 now that has been moved to a separate PR

2022-07-23 15:36 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2022-07-23 15:53 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2022-07-23 16:04 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2022-07-26 16:17 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2022-07-26 16:19 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2022-07-27 10:26 UTC, Pl217 requested changes
Looks to me that rebase was not done perfectly. The first commit is cbf61a656625a8e0efc1802e7d7ba6de54abd116, which is already merged into develop in #315   (8f02d1e7513429b91c5e8192fe5fecc193bfe7f5).

2022-07-27 11:34 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2022-07-27 17:06 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2022-07-27 17:10 UTC, Pl217 approved these changes

2022-07-27 17:10 UTC, merged